# Generated by Django 5.0.13 on 2025-03-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditorReferee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee_email', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='REFEREE_EMAIL', max_length=30, null=True)),
                ('anonymized_article', models.BinaryField(blank=True, db_column='ANONYMIZED_ARTICLE', max_length='max', null=True)),
                ('assessment', models.BinaryField(blank=True, db_column='ASSESSMENT', max_length='max', null=True)),
                ('explanation', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='EXPLANATION', max_length=200, null=True)),
                ('final_assessment_article', models.BinaryField(blank=True, db_column='FINAL_ASSESSMENT_ARTICLE', max_length='max', null=True)),
            ],
            options={
                'db_table': 'editor_referee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='SENDER', max_length=30, null=True)),
                ('message', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='MESSAGE', max_length=400, null=True)),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='TRACKING_NO', max_length=50, null=True)),
                ('owner_email', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='OWNER_EMAIL', max_length=30, null=True)),
                ('raw_article', models.BinaryField(blank=True, db_column='RAW_ARTICLE', max_length='max', null=True)),
            ],
            options={
                'db_table': 'user_editor',
                'managed': False,
            },
        ),
    ]
