# Generated by Django 5.0.13 on 2025-03-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_date', models.DateTimeField(blank=True, null=True)),
                ('log_details', models.CharField(db_collation='Turkish_CI_AS', max_length=255)),
            ],
            options={
                'db_table': 'Logs',
                'managed': False,
            },
        ),
    ]
