# Generated by Django 5.0.13 on 2025-03-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referees',
            fields=[
                ('referee_id', models.IntegerField(db_column='REFEREE_ID', primary_key=True, serialize=False)),
                ('referee_mail', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='REFEREE_MAIL', max_length=30, null=True)),
                ('referee_interests', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='REFEREE_INTERESTS', max_length=200, null=True)),
            ],
            options={
                'db_table': 'referees',
                'managed': False,
            },
        ),
    ]
